package com.askattest.interview.service;

import com.askattest.interview.models.Question;
import com.askattest.interview.models.RespondentStatistics;
import com.askattest.interview.models.Response;
import com.askattest.interview.models.Survey;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * This test class was generated by Gemini
 */
class SurveyStatisticsServiceTest {

    private final SurveyStatisticsService service = new SurveyStatisticsService();

    @Test
    void calculateStatistics_shouldReturnCorrectStats_ForSingleRespondent() {
        // Setup: Survey with 2 questions worth 50p and 100p
        Survey survey = createSurvey(
            createQuestion(1, 50),
            createQuestion(2, 100)
        );

        // Respondent 100 answers both
        List<Response> responses = Arrays.asList(
            createResponse(100, 1),
            createResponse(100, 2)
        );

        Map<Integer, RespondentStatistics> result = service.calculateStatistics(survey, responses);

        assertEquals(1, result.size());
        assertTrue(result.containsKey(100));

        RespondentStatistics stats = result.get(100);
        assertEquals(2, stats.questionsAnswered(), "Should have answered 2 questions");
        assertEquals(150, stats.totalPayout(), "Total payout should be 50 + 100 = 150");
    }

    @Test
    void calculateStatistics_shouldIgnoreResponses_ToQuestionsNotInSurvey() {
        // Setup: Survey only contains Question 1
        Survey survey = createSurvey(createQuestion(1, 50));

        List<Response> responses = Arrays.asList(
            createResponse(100, 1),  // Relevant (belongs to survey)
            createResponse(100, 99)  // Irrelevant (belongs to different survey)
        );

        Map<Integer, RespondentStatistics> result = service.calculateStatistics(survey, responses);

        // Should only count the 1 relevant question
        RespondentStatistics stats = result.get(100);
        assertEquals(1, stats.questionsAnswered());
        assertEquals(50, stats.totalPayout());
    }

    @Test
    void calculateStatistics_shouldCalculateSeparately_ForMultipleRespondents() {
        Survey survey = createSurvey(createQuestion(1, 10));

        List<Response> responses = Arrays.asList(
            createResponse(101, 1),
            createResponse(102, 1)
        );

        Map<Integer, RespondentStatistics> result = service.calculateStatistics(survey, responses);

        assertEquals(2, result.size());
        assertEquals(10, result.get(101).totalPayout());
        assertEquals(10, result.get(102).totalPayout());
    }

    @Test
    void calculateStatistics_shouldReturnEmptyMap_WhenNoResponsesMatchSurvey() {
        Survey survey = createSurvey(createQuestion(1, 10));

        // Responses exist, but none match the survey Question IDs
        List<Response> responses = Arrays.asList(
            createResponse(100, 99),
            createResponse(200, 88)
        );

        Map<Integer, RespondentStatistics> result = service.calculateStatistics(survey, responses);

        assertTrue(result.isEmpty(), "Result should be empty if no relevant responses found");
    }

    @Test
    void calculateStatistics_shouldHandleEmptyResponseList() {
        Survey survey = createSurvey(createQuestion(1, 10));
        List<Response> responses = Collections.emptyList();

        Map<Integer, RespondentStatistics> result = service.calculateStatistics(survey, responses);

        assertTrue(result.isEmpty());
    }

    private Survey createSurvey(Question... questions) {
        Survey survey = new Survey();
        survey.questions = Arrays.asList(questions);
        return survey;
    }

    private Question createQuestion(int id, int payout) {
        Question q = new Question();
        q.id = id;
        q.payout = payout;
        return q;
    }

    private Response createResponse(int respondentId, int questionId) {
        Response r = new Response();
        r.respondent = respondentId;
        r.question = questionId;
        return r;
    }
}